### ISSUE TITLE
Add file reader

### ISSUE THREAD

**Issue by godber** [terascope/file-assets#15]
There is no simple uncompressed file reader in this asset.  There should be.

Some form of this https://github.com/terascope/teraslice_file_import should be incorporated into this asset.  But it should probably use the file chunker if it doesn't already.

**Comment by kstaken** [comment]
This should actually be the most similar to the hdfs_reader. Basically we would want the same behavior as the hdfs_reader except reading the data out of a gluster volume. Since gluster is just a mount on the container this reader should also allow working on local files in a single node deployment.

It should work on sets of files in a directory where a set of files may just be one and each file should be read concurrently across many workers.

I believe the underlying library has what's required since @erik-stephens was able to use it in the compressed file reader.

**Comment by macgyver603** [comment]
This is addressed with #16

**Comment by macgyver603** [comment]
Also tagged the new version for the latest [release](https://github.com/terascope/file-assets/releases/tag/v0.3.0).
